export declare const APP_NAME = "yank-note";
export declare const HOME_DIR: string;
export declare const USER_DIR: string;
export declare const CONFIG_FILE: string;
export declare const STATIC_DIR: string;
export declare const HELP_DIR: string;
export declare const ASSETS_DIR: string;
export declare const HISTORY_DIR: string;
export declare const USER_PLUGIN_DIR: string;
export declare const USER_THEME_DIR: string;
export declare const USER_EXTENSION_DIR: string;
export declare const USER_DATA: string;
export declare const BIN_DIR: string;
export declare const RESOURCES_DIR: string;
export declare const BUILD_IN_STYLES: string[];
export declare const PANDOC_REFERENCE_FILE = "pandoc-reference.docx";
export declare const GITHUB_URL = "https://github.com/purocean/yn";
export declare const FLAG_DISABLE_SERVER = false;
export declare const FLAG_DISABLE_DEVTOOL = false;
